name: battle_render.bin
sha1: 035161ef7e9d3e7122649c3841f193e12c189589
options:
  basename: battle_render
  target_path: original/battle_render.bin
  elf_path: build/ovl/battle_render/battle_render.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/battle_render
  src_path: src/ovl/battle_render
  build_path: build/ovl/battle_render

  # Linker
  ld_script_path: config/battle_render.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True
  disassemble_all: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.battle_render.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.battle_render.txt
  undefined_syms_auto_path: config/undefined_syms_auto.battle_render.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".rodata", ".text", ".data", ".bss"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: battle_render
    type: code
    start: 0x0
    vram: 0x80098000
    subsegments:
      - [0x0, rodata, battle_render_str]
      - [0x238, c, battle_render]
      - [0x353C, bin]
  - [0x139F8]
