name: battle_code.bin
sha1: fa3b045925c0cc8855b321f5dd22ff196f9d51b0
options:
  basename: battle_code
  target_path: original/battle_code.bin
  elf_path: build/ovl/battle_code/battle_code.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/battle_code
  src_path: src/ovl/battle_code
  build_path: build/ovl/battle_code

  # Linker
  ld_script_path: config/battle_code.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.battle_code.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.battle_code.txt
  undefined_syms_auto_path: config/undefined_syms_auto.battle_code.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data", ".bss"]
  subalign: 2
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: battle_code
    type: code
    start: 0x0
    vram: 0x80098000
    subsegments:
      - [0x0, asm, bc_dispatch]
      - [0x1FE8, c, bc_object1]
      - [0x3AC4, c, bc_object2]
      - [0x98E0, c, bc_object3]
      - [0xE184, c, bc_object4]
      - [0x10B7C, c, bc_object5]
      - [0x134A8, c, bc_object6]
      - [0x17358, c, bc_object7]
      - [0x19624, c, bc_object8]
      - [0x1C9D8, c, bc_object9]
      - [0x2072C, c, bc_object10]
      - [0x22EE8, c, bc_object11]
      - [0x270E8, c, bc_object12]
      - [0x2AB88, c, bc_object13]
      - [0x2CA64, c, bc_object14]
      - [0x2F294, c, bc_object15]
      - [0x31F68, c, bc_object16]
      - [0x37F2C, c, bc_object17]
      - [0x3B25C, c, bc_object18]
      - [0x3EAF4, c, bc_object19]
      - [0x40FA4, c, bc_object20]
      - [0x451B0, c, bc_object21]
      - [0x4860C, c, bc_object22]
      - [0x4D724, c, bc_object23]
  - [0x54C48]
