name: field_engine_alt.bin
sha1: b421bf83a307dcd41536b14dc81a3aa03f7c9ed0
options:
  basename: field_engine_alt
  target_path: original/field_engine_alt.bin
  elf_path: build/ovl/field_engine_alt/field_engine_alt.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  # Directory layout
  asm_path: asm/ovl/field_engine_alt
  src_path: src/ovl/field_engine_alt
  build_path: build/ovl/field_engine_alt

  # Linker
  ld_script_path: config/field_engine_alt.ovl.ld
  ld_dependencies: True
  ld_align_section_vram_end: False
  ld_align_segment_vram_end: False

  # Analysis
  find_file_boundaries: True

  # Symbols
  symbol_addrs_path:
    - config/symbol_addrs.field_engine_alt.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.field_engine_alt.txt
  undefined_syms_auto_path: config/undefined_syms_auto.field_engine_alt.txt

  # String detection
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Misc
  section_order: [".text", ".rodata", ".data", ".bss"]
  subalign: 1
  o_as_suffix: True
  use_legacy_include_asm: False
  generate_asm_macros_files: False

segments:
  - name: field_engine_alt
    type: code
    start: 0x0
    vram: 0x80098000
    subsegments:
      - [0x0, c, fea_dispatch]
      - [0x17E8, c, fea_object1]
      - [0x4CE8, c, fea_object2]
      - [0x81DC, c, fea_object3]
      - [0xE4DC, c, fea_object4]
      - [0x1336C, c, fea_object5]
      - [0x14C68, c, fea_object6]
      - [0x1B10C, c, fea_object7]
      - [0x20CE0, c, fea_object8]
      - [0x22870, c, fea_object9]
      - [0x256EC, c, fea_object10]
      - [0x275D4, c, fea_object11]
      - [0x2B898, c, fea_object12]
      - [0x2C0F8, c, fea_object13]
      - [0x300F8, c, fea_object14]
      - [0x30634, bin]
  - [0x30635]
