#!/usr/bin/env python3
"""Asset pipeline tool for ff8-decomp.

Converts binary assets into C source files for compilation.

Usage:
    assets.py build <config.yaml>     Build all assets from config
    assets.py build <config.yaml> <name>  Build a single asset by name

Config format (YAML):
    assets:
      - name: field_init_font
        source: assets/field_init_font.tim
        symbol: D_80098500
        header: src/ovl/field_init/field_init_font.h
        output: src/ovl/field_init/field_init_tim.c
"""
import os
import sys

import yaml


def bin_to_c(data, symbol, header, ctype="u8"):
    """Convert binary data to a C source file string."""
    import struct as st
    lines = []
    lines.append("/* Auto-generated by assets.py — do not edit */")
    lines.append(f'#include "{header}"')
    lines.append("")

    if ctype == "u32":
        while len(data) % 4:
            data += b"\x00"
        count = len(data) // 4
        words = st.unpack(f"<{count}I", data)
        lines.append(f"u32 {symbol}[] = {{")
        for i in range(0, len(words), 8):
            chunk = words[i:i+8]
            line = ", ".join(f"0x{w:08X}" for w in chunk)
            if i + 8 < len(words):
                line += ","
            lines.append(f"    {line}")
    else:
        lines.append(f"u8 {symbol}[] = {{")
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            line = ", ".join(f"0x{b:02X}" for b in chunk)
            if i + 16 < len(data):
                line += ","
            lines.append(f"    {line}")

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def build_asset(asset, base_dir):
    """Build a single asset entry."""
    source = os.path.join(base_dir, asset["source"])
    output = os.path.join(base_dir, asset["output"])
    symbol = asset["symbol"]
    header = asset["header"]

    if not os.path.exists(source):
        print(f"  SKIP {asset['name']}: {source} not found", file=sys.stderr)
        return False

    with open(source, "rb") as f:
        data = f.read()

    ctype = asset.get("type", "u8")
    c_src = bin_to_c(data, symbol, header, ctype)

    os.makedirs(os.path.dirname(output), exist_ok=True)
    with open(output, "w") as f:
        f.write(c_src)

    print(f"  {asset['name']}: {source} -> {output} ({len(data)} bytes)")
    return True


def build(config_path, name_filter=None):
    """Build assets from config file."""
    # Project root is the directory containing the config directory
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(config_path)))

    with open(config_path) as f:
        config = yaml.safe_load(f)

    assets = config.get("assets", [])
    if name_filter:
        assets = [a for a in assets if a["name"] == name_filter]
        if not assets:
            print(f"Error: asset '{name_filter}' not found in config", file=sys.stderr)
            sys.exit(1)

    for asset in assets:
        build_asset(asset, base_dir)


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} build <config.yaml> [<name>]", file=sys.stderr)
        sys.exit(1)

    cmd = sys.argv[1]
    config_path = sys.argv[2]
    name_filter = sys.argv[3] if len(sys.argv) > 3 else None

    if cmd == "build":
        build(config_path, name_filter)
    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
