#!/usr/bin/env python3
"""Convert a binary file to a C array.

Usage: bin2c.py <input.bin> <symbol_name> <c_type> [<output.h>]

Writes a C array definition to stdout or the given output file.
Example: bin2c.py font.tim D_80098500 u32 font.h
"""
import struct
import sys

def main():
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <input> <symbol> <type> [<output>]", file=sys.stderr)
        sys.exit(1)

    bin_path = sys.argv[1]
    symbol = sys.argv[2]
    c_type = sys.argv[3]
    out_path = sys.argv[4] if len(sys.argv) > 4 else None

    with open(bin_path, "rb") as f:
        data = f.read()

    lines = []
    lines.append("/* Auto-generated by bin2c — do not edit */")
    lines.append('#include "common.h"')
    lines.append("")

    if c_type == "u32":
        # Pad to 4-byte alignment if needed
        while len(data) % 4:
            data += b"\x00"
        count = len(data) // 4
        words = struct.unpack(f"<{count}I", data)
        lines.append(f"u32 {symbol}[] = {{")
        for i in range(0, len(words), 8):
            chunk = words[i:i+8]
            line = ", ".join(f"0x{w:08X}" for w in chunk)
            if i + 8 < len(words):
                line += ","
            lines.append(f"    {line}")
        lines.append("};")
    else:
        lines.append(f"u8 {symbol}[] = {{")
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            line = ", ".join(f"0x{b:02X}" for b in chunk)
            if i + 16 < len(data):
                line += ","
            lines.append(f"    {line}")
        lines.append("};")

    lines.append("")
    output = "\n".join(lines)

    if out_path:
        with open(out_path, "w") as f:
            f.write(output)
    else:
        print(output)

if __name__ == "__main__":
    main()
