#!/usr/bin/env python3
"""Write the battle effect overlays into the binary map in config/ff8.yaml.

There are hundreds of these and their segment bounds are all measured from the
images rather than chosen by hand, so this block of the config is generated
rather than edited. Everything between the BEGIN/END marker comments at the end
of `binaries:` is replaced; the rest of the file is left alone. Re-run after
`tools/extract.py`; `--check` fails if the block is stale.

Each code overlay becomes a `code` segment at the link base recovered by
tools/battle_effect_overlays.py, with `.text` running to the first word that is
not a legal instruction. Everything after that is the overlay's embedded asset
payload -- roughly 85% of the image -- and is emitted as `bin`, not `data`:
disassembling it produces a `.word` listing about 12x the size of the bytes it
describes, which across the whole set is gigabytes of asm nobody reads. Promote
a region to `data` per overlay when its tables are actually being worked on.

Overlays whose link base cannot be established, and the AKAO sound bundles that
share the table, are `bin` throughout, so they still build byte-exactly without
being disassembled at a base that is only a guess.

Usage: gen_effect_config.py [-o config/ff8.yaml] [--check]
"""
import argparse
import hashlib
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import battle_effect_overlays as effects

BEGIN = ("# BEGIN battle effect overlays -- generated by "
         "tools/gen_effect_config.py\n")
END = "# END battle effect overlays\n"

HEADER = BEGIN + """\
#
# One binary per battle action id, extracted from the disc by tools/extract.py.
# Segment bounds are measured from the images, not chosen by hand, so this block
# is rewritten by the generator rather than edited. Everything outside the
# markers is untouched. See docs/battle-effect-overlays.md.
#
"""


def rodata_extent(image, base, text):
    """-> byte offset where the pointer-table rodata after .text ends.

    Every overlay puts its opcode dispatch tables immediately after the code,
    as runs of pointers back into its own .text. They have to be a `.rodata`
    subsegment rather than part of the asset blob, because they are local array
    initialisers in the C and so must be emitted by the compiler.
    """
    off = text
    while off + 4 <= len(image):
        word = struct.unpack_from("<I", image, off)[0]
        if not (base <= word < base + text and (word - base) % 4 == 0):
            break
        off += 4
    return off


def entries():
    table = effects.table()
    out = []
    for index in range(effects.FIRST_INDEX, effects.TABLE_ENTRIES):
        if table[index][1] == 0:
            continue
        effect_id = index - effects.ID_BIAS
        image = effects.load(effect_id)
        if image is None:
            sys.exit("original/effect is missing; run tools/extract.py first")
        name = "effect_%03d" % effect_id
        sha1 = hashlib.sha1(image).hexdigest()
        akao = image[8:12] == b"AKAO"
        base, text, _hits, _targets = effects.link_base(image)
        rodata = None
        if base is not None and not akao:
            end = rodata_extent(image, base, text)
            if end > text:
                rodata = end
        out.append((name, sha1, len(image), None if akao else base, text, rodata))
    return out


def render(rows):
    lines = [HEADER]
    for name, sha1, size, base, text, rodata in rows:
        lines.append("- name: %s\n  sha1: %s\n" % (name, sha1))
        lines.append("  options: {target_path: original/effect/%s.bin, "
                     "src_path: src/effect}\n" % name)
        if base is None:
            lines.append("  segments:\n  - [0x0, bin, %s]\n  - [0x%X]\n"
                         % (name, size))
        else:
            if rodata:
                subs = ("[[0x0, c, %s], [0x%X, .rodata, %s], [0x%X, bin, %s]]"
                        % (name, text, name, rodata, name))
            else:
                subs = "[[0x0, c, %s], [0x%X, bin, %s]]" % (name, text, name)
            lines.append("  segments:\n"
                         "  - {name: %s, type: code, start: 0, vram: 0x%08X,\n"
                         "     subsegments: %s}\n"
                         "  - [0x%X]\n"
                         % (name, base, subs, size))
    lines.append(END)
    return "".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", default="config/ff8.yaml")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    old = open(args.out).read()
    block = render(entries())
    if BEGIN in old:
        head = old[:old.index(BEGIN)]
        tail = old[old.index(END) + len(END):]
    else:
        head, tail = old.rstrip("\n") + "\n", ""
    new = head + block + tail

    if new == old:
        return 0
    if args.check:
        print("stale effect overlay block in %s "
              "(run tools/gen_effect_config.py)" % args.out)
        return 1
    with open(args.out, "w") as fh:
        fh.write(new)
    return 0


if __name__ == "__main__":
    sys.exit(main())
